legacy:
  server: http://localhost:8080

hsm:
  server: http://localhost:8082

coinstack:
  endpoint: http://krxpoc-node.blocko.io
  server:
    privatekeys: L3k5T3xBc6kc3owCHak84R14yyCQW5WQSPRBs3kNaZtdjyC2uyfZ

server:
  facility: KRX
  hostname: localhost
  port: 9080

kafka:
  endpoint: PLAINTEXT://13.124.144.20:9092,PLAINTEXT://13.209.189.39:9092,PLAINTEXT://52.79.238.211:9092,PLAINTEXT://54.180.173.79:9092,PLAINTEXT://54.180.168.207:9092,PLAINTEXT://52.78.95.78:9092,PLAINTEXT://54.180.181.191:9092
  #endpoint: PLAINTEXT://192.168.0.191:9092, PLAINTEXT://192.168.0.192:9092
spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  liquibase:
    change-log: classpath:/db/krx-changelog-master.yaml
  datasource:
    initialize: true
    username: blocko
    password: blocko
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL
    validationQuery: SELECT 1
  devtools:
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
      globally_quoted_identifiers: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format_sql: true
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    jadira:
      usertype:
        autoRegisterUserTypes: true
    show-sql: true

management:
    endpoints:
        web:
            exposure:
                include: '*'
            base-path: /manage
        enabled-by-default: false
    endpoint:
        health:
            enabled: true
        shutdown:
            enabled: true
